---
title: "Assignment 1"
author: "David Ludeke"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document
---

```{r setup, include = F}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
library(tidyverse)
```

```{r library_load}
library(tidyverse)
library(plotly)
library(sf)
library(tigris)
library(leaflet)
library(censusapi)

Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")
```

```{r save_point}
# SAVE POINT
save.image("progress1.rda")
```


```{r data_extraction} 
years <- 2017:2021
quarters <- 1:4
types <- c("Electric", "Gas")

pge_elec_raw <- NULL
pge_gas_raw <- NULL

# Loop through years
for (year in years) {
  # Loop through quarters
  for (quarter in quarters) {
    # Loop through gas & electric
    for (type in types) {
      filename <-
        paste0("pge_data/PGE_",
               year,
               "_Q",
               quarter,
               "_",
               type,
               "UsageByZip.csv")
      
      # Skip if file doesn't exist
      if (!file.exists(filename))
        next
      
      temp <- read_csv(filename)
      
      if (type == "Electric") {
        # Convert KWh to KTBU and eliminate extra columns
        temp <- temp %>%
          mutate(TOTALKTBU = TOTALKWH * 3.41214) %>%
          select(-TOTALKWH, -AVERAGEKWH, -COMBINED)
        # bind to raw data
        pge_elec_raw <- rbind(pge_elec_raw, temp)
      } else { # Otherwise type is Gas
        # Convert therms to KTBU and delete extra columns 
        temp <- temp %>%
          mutate(TOTALKTBU = TOTALTHM * 99.9761) %>% 
          select(-TOTALTHM, -AVERAGETHM, -COMBINED)
        # bind to raw data
        pge_gas_raw <- rbind(pge_gas_raw, temp)
      }
    }
  }
  # Save after binding each year together
  saveRDS(pge_elec_raw, "pge_elec_raw.rds")
  saveRDS(pge_gas_raw, "pge_elec_raw.rds")
}

# Combine raw dataframes together
pge_data_raw <- rbind(pge_elec_raw, pge_gas_raw)

```

```{r manipulate_data}
pge_data <- pge_data_raw %>% 
  filter(
    CUSTOMERCLASS %in% c("Elec- Residential", "Elec- Commercial", 
                         "Gas- Residential", "Gas- Commerical")) %>%
  group_by(
    MONTH, YEAR, CUSTOMERCLASS, TOTALKTBU) %>%
  summarize(
    
  )


```


## Residential Data
```{r residential_plot}

```

## Commercial Data
```{r commercial_plot}

```

