---
title: "DavidLudeke_A6"
author: "David Ludeke"
date: "10/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

```{r}
library(censusapi)
library(tidyverse)
library(tigris)
library(sf)
library(leaflet)

Sys.setenv(CENSUS_KEY="46c0518594422fc024772060dae78c2c2ffcc89d")
```

```{r}
# analyze at household level 

# pums_2019_1yr <- getCensus(
#   name = "acs/acs1/pums",
#   vintage = 2019,
#   region = "public use microdata area:*", 
#   regionin = "state:06",
#   vars = c(
#     "SERIALNO",
#     "SPORDER",
#     "PWGTP",
#     "WGTP",
#     "YBL", # new variables... v
#     "BLD", 
#     "TEN", 
#     "MV", 
#     "HINCP", 
#     "AGEP"
#   )
# )

# saveRDS(pums_2019_1yr, "a6_pums.rds")

pums_2019_1yr <- readRDS("a6_pums.rds")
```


```{r}

ca_pumas <-
  pumas("CA", cb = T, progress_bar = F)

sf_boundary <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME == "San Francisco")

sf_pumas <-
  ca_pumas %>% 
  st_centroid() %>% 
  .[sf_boundary, ] %>% 
  st_drop_geometry() %>% 
  left_join(ca_pumas %>% select(GEOID10)) %>% 
  st_as_sf()
```


```{r}
sf_pums <- pums_2019_1yr %>% 
  mutate(
    PUMA = str_pad(public_use_microdata_area,5,"left", "0")
  ) %>% 
  filter(PUMA %in% sf_pumas$PUMACE10)
```


```{r}
# Filter to housing structures before 1960
sf_pums_clean <- sf_pums %>% 
  mutate(
    YBL = as.numeric(YBL),
    AGEP = as.numeric(AGEP),
    HINCP = as.numeric(HINCP)
  ) %>% 
  filter(YBL %in% 1:3) %>% 
  arrange(AGEP) %>% # start with youngest people
  group_by(SERIALNO) %>%  # keep unique values for household
  summarize_all(first) %>% # keep first value from each field
  mutate( 
    leadrisk = ifelse( # only include entries with income < 90k and age <= 6
      HINCP <= 90000 & AGEP <= 6,
      1, 
      0
    )
  ) %>%
  mutate(across(
    c(BLD, TEN, YBL, WGTP, MV, HINCP, PUMA),
    factor
    )
  )

```

```{r}
logit_model <- glm(
  leadrisk ~ BLD + TEN + MV + PUMA,
  family = quasibinomial(),
  data = sf_pums_clean
)

summary(logit_model)

```

One-row sample prediction:
```{r}
# Run on a sample of one entry in sf_pums_clean
one_row_sample <- sample_n(sf_pums_clean, 1)
predict(logit_model, 
        one_row_sample, 
        type = "response"
)

```

